---
- name: Make sure python OpenSSL is installed
  yum: 
    name: 
      - pyOpenSSL
      - python2-cryptography
    state: latest
    lock_timeout: 180

- name: Make sure python3-oci-cli is installed
  yum:
    name:
      - python36-oci-cli
    state: latest
    lock_timeout: 180
